name: TransIP DDNS Updater
version: 1.0
slug: transip-ddns-updater
description: Update DNS records for dynamic ip-addresses
url: https://github.com/MarcRuemekorf/transip-ddns-updater
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
    username: ""
    token: ""
    domain: ""
    record: ""
    interval: 300
schema:
    username: str
    token: str
    domain: str
    record: str
    interval: int